version: '3.8'

services:
  app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - mysql
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true

  mysql:
    container_name: mysql
    image: mysql:8
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    volumes:
      - './data:/var/lib/mysql'

