version: '3.8'

services:
  mysql:
    container_name: mysql
    image: mysql:8
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    volumes:
      - './data:/var/lib/mysql'
  supertoken:
    container_name: supertoken
    image: registry.supertokens.io/supertokens/supertokens-mysql
    depends_on:
      - mysql
    environment:
      MYSQL_CONNECTION_URI: "mysql://supertoken:supertoken@mysql:3306"
      MYSQL_USER: 'supertoken'
      MYSQL_PASSWORD: 'supertoken'
    ports:
      - '3567:3567'