module.exports = Object.freeze({
    FULL_TIME_MAX_HOUR: 40,
    PART_TIME_MAX_HOUR: 20,

    // OFF_REQUEST_STATUS 
    OFF_REQUEST_STATUS_APPROVE: 2,
    OFF_REQUEST_STATUS_DENIED: 3,
    OFF_REQUEST_STATUS_PENDING: 1,

})